### ISSUE TITLE
Icon disappears on toggle

### ISSUE THREAD

**Issue by birkanucan** [yursan9/budgie-caffeine-applet#13] opened 2018-05-01 13:00 UTC
Icon disappears on toggle (Solus) 
![peek 2018-05-01 15-58](https://user-images.githubusercontent.com/9096751/39473701-c05ae3da-4d58-11e8-9075-5319782bb0ae.gif)

**Comment by yursan9** [comment] 2018-05-02 08:44
Can't reproduce the issue.
![can t reproduce](https://user-images.githubusercontent.com/17114559/39513752-8c0f6e1c-4e1f-11e8-9976-73c83501db18.gif)

Did you try to remove and re-add the applet?

**Comment by birkanucan** [comment] 2018-05-02 18:10
yes, also tried to reinstall, neither helped

**Comment by yursan9** [comment] 2018-05-02 18:14
Okay, can you remove the applet and tried running commands below in terminal?
```
budgie-panel --replace
```

After that, add the applet to panel, try to toggling the applet, and paste the output of terminal.

**Comment by birkanucan** [comment] 2018-05-02 18:29
![screenshot from 2018-05-02 21 21 06](https://user-images.githubusercontent.com/9096751/39541954-dd2fc92e-4e4f-11e8-80ba-cfc7e48f24e3.png)

**Comment by yursan9** [comment] 2018-05-02 18:32
Okay, this is duplicate of issue #12.
I'll close this and you can subscribe to the other issue.

**Closed as completed by yursan9** 2018-05-02 18:32 UTC

**Comment by birkanucan** [comment] 2018-05-02 18:35
ok but when I end the process "budgie-panel --replace", the panel disappears, what should I do?

**Comment by yursan9** [comment] 2018-05-02 18:37
You can run the command again, and restart your computer when the panel show up, if you still need to use your computer just leave the process in another terminal.

**Comment by birkanucan** [comment] 2018-05-02 18:40
oh, so there isn't a proper way to cancel out from it then. ^^ ok thanks anyway.

**Comment by birkanucan** [comment] 2018-05-02 18:50
btw I made a request on transifex for turkish translation, so if you could approve it I can make the translation right away.
