### ISSUE TITLE
Activating timer after enabling caffeine is null

### ISSUE THREAD

**Issue by gazny** [yursan9/budgie-caffeine-applet#5] opened 2017-09-26 15:54 UTC
Activating caffeine than setting a timer does not override the indefinite time set by caffeine.

**Comment by yursan9** [comment] 2017-09-27 14:58
It was the intended behavior. I need to disable timer widget when the caffeine mode was activated.

**Comment by yursan9** [comment] 2017-09-29 11:19
I'll close this. The master branch already get the fix.

**Closed as completed by yursan9** 2017-09-29 11:19 UTC
